Skip FocusOut exit if focus was quickly returned
p-e-w/shin pull request #8
Opened 2022-10-30 10:58 UTC by Zachu

This addresses the discussion in #5

2022-10-31 04:22 UTC, p-e-w requested changes

2022-10-31 04:22 UTC, p-e-w commented on main.go
> +	if time.Now().UnixMilli() < e.startTime + 250 {
Instead of manually working with milliseconds, store the `Time` object itself in `engine`, then compare with

```go
time.Since(e.startTime) < 250 * time.Millisecond
```

Not only is this cleaner and more idiomatic, it also uses the monotonic clock rather than the wall clock, which avoids (rare) complications when the system clock is adjusted.

2022-10-31 04:22 UTC, p-e-w commented on main.go
> +	e.startTime = time.Now().UnixMilli()
Insert blank line before this statement, in line with the style of the other methods.

2022-10-31 04:22 UTC, p-e-w commented on main.go
> +	// TODO: The timeout or the whole functionality could be made configurable
I think this TODO can be removed. This is an implementation detail, not a user-facing option. If the timeout turns out to be insufficient, that's a bug and it should be increased or another solution should be found. But the user shouldn't have to fiddle with configurations just to get Shin to work.

2022-10-31 06:35 UTC, Zachu commented on main.go
> +	if time.Now().UnixMilli() < e.startTime + 250 {
I definitely agree with this one. First time touching Go so this was definitely a welcome pointer! =) Thanks!

2022-10-31 06:38 UTC, Zachu commented on main.go
> +	// TODO: The timeout or the whole functionality could be made configurable
With your reasoning I totally agree. I think my mind went a bit too engineering-y in this one. And I think this is a problem in many Open Source projects actually. Especially in this case where the small grace period in the FocusOut exit functionality is not expected to cause issues to anyone we definitely don't need a dozen of knobs to turn :)

2022-10-31 06:40 UTC, Zachu commented
Applied the requested changes. Huge thanks for thoughtful review and stating your reasoning for the changes!

2022-11-01 04:44 UTC, p-e-w approved these changes

2022-11-01 04:53 UTC, merged

2022-11-01 04:57 UTC, p-e-w commented
Merged. Thank you for this valuable contribution!